config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]


end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  album_style :string           not null
#  band_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Album < ActiveRecord::Base

  ALBUM_STYLE = %w(live studio)

  validates(
    :name,
    :album_style,
    :band_id,
    :band,
    presence: true
  )

   validates :album_style, inclusion: ALBUM_STYLE

   has_many :tracks, dependent: :destroy

   belongs_to :band

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :force_log_in

  def new
    band = Band.find(params[:band_id])
    @album = Album.new(band_id: band.id)
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    flash.notice = "Album '#{@album.name}' Destroyed!"
    redirect_to bands_url

  end

  private
  def album_params
    params.require(:album).permit(:name, :album_style)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.erb
<h1>Edit <%= @album.name %></h1>

<%= render "shared/errors" %>
<%= render "shared/form_album", url: album_url(@album), method: "PATCH", album: @album %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render "shared/errors" %>
<%= render "shared/form_album", url: albums_url, method: "POST", album: @album %>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<!-- <%#= render "shared/edit", album: @album %> -->
<%= button_to "Edit Album", edit_album_url(@album), method: :get %>
<%= button_to "Delete Album", album_url(@album), method: :delete %>
<%= button_to "New #{@album.name} Track", new_album_track_url(@album), method: :get %>