config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]


end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

  has_many :albums, dependent: :destroy

  has_many :tracks,
  through: :albums,
  source: :tracks


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :force_log_in

  def index

  end

  def new
    @band = Band.new
  end

  def create
  end

  def show
    @band = Band.find(params[:id])
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    flash.notice = "Band '#{@band.name}' Deleted!"
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %> </h1>

<%= render "shared/errors" %>
<%= render "shared/form_band", url: band_url(@band), method: "PATCH", band: @band%>

app/views/bands/index.html.erb
<br>

<%= flash.notice %>

<ul>
  <% Band.all.each do |band| %>
    <li><%= link_to "#{band.name}", band_url(band) %></li>
  <% end %>
</ul>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<%#= render "shared/show", band: @band %>
<h2>Albums</h2>
<ul>
  <% @band.albums.each do |album| %>
    <li><%= album.name %></li>
  <% end %>
</ul>

<%= button_to "Edit Band", edit_band_url(@band), method: :get %>
<%= button_to "Delete Band", band_url(@band), method: :delete %>
<%= button_to "New #{@band.name} Album", new_band_album_url(@band), method: :get %>